services:
  web:
    container_name: ${PROJECT_PREFIX}_web
    build: .
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:17-alpine
    container_name: ${PROJECT_PREFIX}_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:latest
    container_name: ${PROJECT_PREFIX}_cache
    ports:
      - "6380:6379"
  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: sh -c "celery -A library_grade worker --loglevel=info"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  db_data: